version: '3.4'

services:
    
  db:
    image: mysql:latest
    networks: 
      - node_app
    command: --default-authentication-plugin=mysql_native_password

  node:
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${NODE_PORT}
    networks:
      - node_app

networks: 
  node_app: